name: Deploy to Test Environment

on:
  push:
    branches:
      - test-production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to test
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_SSH_HOST }}
          username: ${{ secrets.TEST_SSH_USERNAME }}
          key: ${{ secrets.TEST_SSH_KEY }}
          port: 43789
          script: |
            cd ~/git/frontend
            git pull origin test-production
            docker compose -f docker-compose.test.yml up -d --build --remove-orphans
